apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "telecom-chart.fullname" . }}
  labels:
    {{- include "telecom-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "telecom-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "telecom-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 3
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: telecom-secret
              key: database-url
        - name: REDIS_HOST
          value: {{ .Values.redis_host | default "redis" }}
