{{- if .Values.hpa.enabled }}       # Helm template для HPA (только если включён)   # условие: если hpa.enabled=true
apiVersion: autoscaling/v2     
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "telecom-chart.fullname" . }}
  labels:
    {{- include "telecom-chart.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "telecom-chart.fullname" . }}     # Deployment для скейлинга
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.targetCPUUtilizationPercentage }} # процент из values.yaml
{{- end }}  # конец условия
