apiVersion: v1 # Helm template для Service
kind: Service
metadata:
  name: {{ include "telecom-chart.fullname" . }}  # имя
  labels:
    {{- include "telecom-chart.labels" . | nindent 4 }}    # лейблы
spec:
  type: {{ .Values.service.type }}        # тип из values.yaml
  ports:
    - port: {{ .Values.service.port }}     # порт
      targetPort: http             # targetPort
      protocol: TCP
      name: http
  selector:
    {{- include "telecom-chart.selectorLabels" . | nindent 4 }}     # селектор
