apiVersion: v1    # PersistentVolumeClaim — запрос хранилища для PostgreSQL
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce                    # мониторинг одним узлом (одиночный write)
  resources:
    requests:
      storage: 1Gi                      # запрос 1 ГБ хранилища
