apiVersion: v1
kind: Secret
metadata:
  name: telecom-secret
type: Opaque
stringData:
  database-url: "postgresql://telecom:telecompass@postgres:5432/telecom"
  db-user: "telecom"
  db-password: "telecompass"
