apiVersion: v1
kind: Secret
metadata:
  name: telecom-secret       # имя Secret'а
type: Opaque                  # тип: произвольные данные (не специфичный тип)
stringData:                   # данные в открытом виде (K8s сам зашифрует)
  database-url: "postgresql://telecom:telecompass@postgres:5432/telecom"
  db-user: "telecom"
  db-password: "telecompass"
