replicaCount: 3 # Количество реплик (если HPA не включён)

image:      # Конфигурация Docker образа
  repository: telecom-api   # имя образа
  tag: latest #последний
  pullPolicy: IfNotPresent    # policy: если уже есть → не тянуть

service:  # Конфигурация Service'а
  type: ClusterIP  # тип: внутренний
  port: 80   # порт

resources:   # Ресурсы (CPU/mem)
  requests:
    cpu: 100m       # мин CPU
    memory: 128Mi      # мин память
  limits:
    cpu: 200m                 # макс CPU
    memory: 256Mi            # макс память

hpa:                    # HPA (автоскейлинг)
  enabled: true            # включить HPA
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70       # целевая нагрузка CPU

postgresql:      # PostgreSQL (из зависимостей)
  enabled: true        # установить PostgreSQL
  global:
    postgresqlDatabase: telecom
    postgresqlUsername: telecom
    postgresqlPassword: telecompass

redis: # установить Redis
  enabled: true

ingress:      # Ingress
  enabled: false   # отключить (включить для production с доменом)
  hosts:
    - host: telecom.local  # домен
      paths:
        - path: /
          pathType: Prefix
